language: node_js
node_js:
  - "lts/*"

cache:
  yarn: true
  directories:
    - ~/.cache

branches:
  only:
    - master

jobs:
  include:
    - stage: Health Checks
      name: "Cypress E2E Test"
      script: yarn cypress:ci

    - name: "Unit Tests, Lint, and Audit"
      script:
        - yarn test:ci
        - yarn lint
        - yarn audit
